### ISSUE TITLE
Bad position when the parent of image is an transofrm element.

### ISSUE THREAD

**Issue by Angel-Ponce** [carlos-dubon/ng-zoom#1]
For example:

```html
<div class="grid-3" style="transform: translate3d(0,0,0);" id="parent">
    <img
      style="display:block; height: 100%; width: 100%; object-fit: contain"
      ng-zoom
      src="https://source.unsplash.com/800x1000"
      alt="a"
    />
    <img
      style="display:block; height: 100%; width: 100%; object-fit: contain"
      ng-zoom
      src="https://source.unsplash.com/400x200"
      alt="b"
    />
    <img
      style="display:block; height: 100%; width: 100%; object-fit: contain"
      ng-zoom
      src="https://source.unsplash.com/800x587"
      alt="c"
    />
  </div>
```

The element with a `parent` id is a transform element, this broke the `ng-zoom` child elements:

![image](https://user-images.githubusercontent.com/60164099/183297692-18421402-1bcb-4939-b616-f3d6e81ed551.png)

(The example has been taked from your [StackBlitz Demo](https://stackblitz.com/edit/angular-ivy-vgauuz?file=src%2Fapp%2Fapp.component.ts)

**Comment by carlos-dubon** [comment]
Thanks for your contribution and sorry for the late answer.

From the MDN article about Transform: https://developer.mozilla.org/en-US/docs/Web/CSS/transform

> If the property has a value different than none, a [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) will be created. In that case, the element will act as a [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block) for any position: fixed; or position: absolute; elements that it contains.

The issue is indeed in the CSS transform function. Turns out Transform changes the element into a containing block which restrains all the elements inside of it within its dimensional limits. 

## The workaround:
Remove the transform property from the containing block when the image is clicked.
